[0.000000] (-) TimerEvent: {}
[0.003057] (team13_chase_object) JobQueued: {'identifier': 'team13_chase_object', 'dependencies': OrderedDict()}
[0.012200] (team13_chase_object) JobStarted: {'identifier': 'team13_chase_object'}
[0.098929] (-) TimerEvent: {}
[0.200258] (-) TimerEvent: {}
[0.301099] (-) TimerEvent: {}
[0.401974] (-) TimerEvent: {}
[0.503424] (-) TimerEvent: {}
[0.604208] (-) TimerEvent: {}
[0.705003] (-) TimerEvent: {}
[0.805903] (-) TimerEvent: {}
[0.906824] (-) TimerEvent: {}
[1.008648] (-) TimerEvent: {}
[1.109697] (-) TimerEvent: {}
[1.210423] (-) TimerEvent: {}
[1.311149] (-) TimerEvent: {}
[1.411930] (-) TimerEvent: {}
[1.512703] (-) TimerEvent: {}
[1.613681] (-) TimerEvent: {}
[1.714799] (-) TimerEvent: {}
[1.815532] (-) TimerEvent: {}
[1.916837] (-) TimerEvent: {}
[2.018090] (-) TimerEvent: {}
[2.119263] (-) TimerEvent: {}
[2.220098] (-) TimerEvent: {}
[2.286038] (team13_chase_object) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.10/selectors.py", line 469, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 105, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 81, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 171, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 128, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "/home/burger/CS-7785/lab_3/team13_chase_object/setup.py", line 5, in <module>\n    setup(\n  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 107, in setup\n    return distutils.core.setup(**attrs)\n  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 172, in setup\n    ok = dist.parse_command_line()\n  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 472, in parse_command_line\n    if self.handle_display_options(option_order):\n  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1209, in handle_display_options\n    return _Distribution.handle_display_options(self, option_order)\n  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 686, in handle_display_options\n    self.print_commands()\n  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 988, in print_commands\n    cmdclass = ep.load()\n  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load\n    module = import_module(match.group(\'module\'))\n  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 8, in <module>\n    from setuptools.command.easy_install import easy_install\n  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 50, in <module>\n    from setuptools.sandbox import run_setup\n  File "/usr/local/lib/python3.10/dist-packages/setuptools/sandbox.py", line 13, in <module>\n    import pkg_resources\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3328, in <module>\n    def _initialize_master_working_set():\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3302, in _call_aside\n    f(*args, **kwargs)\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 622, in _build_master\n    ws = cls()\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 615, in __init__\n    self.add_entry(entry)\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 671, in add_entry\n    for dist in find_distributions(entry, True):\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2134, in find_on_path\n    for dist in factory(fullpath):\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2199, in distributions_from_metadata\n    yield Distribution.from_location(\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2673, in from_location\n    )._reload_version()\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3081, in _reload_version\n    md_version = self._get_version()\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2858, in _get_version\n    version = _version_from_file(lines)\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2624, in _version_from_file\n    line = next(iter(version_lines), \'\')\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2853, in _get_metadata\n    for line in self.get_metadata_lines(name):\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1529, in get_metadata_lines\n    return yield_lines(self.get_metadata(name))\n  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1521, in get_metadata\n    return value.decode(\'utf-8\')\nKeyboardInterrupt\n\n'}
[2.288175] (team13_chase_object) JobEnded: {'identifier': 'team13_chase_object', 'rc': 'SIGINT'}
[2.297936] (-) EventReactorShutdown: {}
